services:
  ingesta-mongo:
    build: ./mongodb
    environment:
      - MONGO_CLIENTE=${MONGO_CLIENT}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./mongodb:/ingesta


  ingesta-mysql:
    build: ./mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE=${MYSQL_TABLE}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./mysql:/ingesta

  ingesta-postgresql:
    build: ./postgresql
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_TABLE=${PG_TABLE}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./postgresql:/ingesta
