services:
  ingesta-mongo:
    build: ./mongodb
    environment:
      - MONGO_CLIENT=${MONGO_CLIENT}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./mongodb:/ingesta
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials


  ingesta-mysql:
    build: ./mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - S3_BUCKET=${S3_BUCKET}
      - MYSQL_TABLES=${MYSQL_TABLES}
    volumes:
      - ./mysql:/ingesta
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials

  ingesta-postgresql:
    build: ./postgresql
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_TABLES=${PG_TABLES}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./postgresql:/ingesta
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
